[[tables]]
name = "stockHistoryDaily"
key = ["dt", "code"]
desc = "股票天极K线"
fetch_function = "fetch_stock_history"

[[tables]]
name = "indexHistoryDaily"
key = ["dt"]
desc = "大盘天级K线"
fetch_function = "fetch_index_history"


[[tables]]
name = "conceptHistoryDaily"
key = ["dt", "name"]
desc = "板块天级K线"
fetch_function = "fetch_concept_history"

[[tables]]
name = "industryHistoryDaily"
key = ["dt", "name"]
desc = "行业天级K线"
fetch_function = "fetch_industry_history"

[[tables]]
name = "stockConcept"
key = ["dt", "name", "code"]
desc = "股票板块"
fetch_function = "fetch_stock_concept"

[[tables]]
name = "stockIndustry"
key = ["dt", "name", "code"]
desc = "股票行业"
fetch_function = "fetch_stock_industry"